###

GET http://localhost:3000/api/health HTTP/1.1



###

GET http://localhost:3000/api/users HTTP/1.1

###

GET http://localhost:3000/api/users/10 HTTP/1.1

###

POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
  "email": "delete@example.com",
  "name": "Delete User"
}

###

PUT http://localhost:3000/api/users/37 HTTP/1.1
Content-Type: application/json

{
  "email": "updatedelete@example.com",
  "name": "Delete User updated"
}

###

DELETE http://localhost:3000/api/users/37 HTTP/1.1

###
# 投稿一覧取得
GET http://localhost:3000/api/posts HTTP/1.1

###
# 特定の投稿を取得
GET http://localhost:3000/api/posts/5 HTTP/1.1

###
# 投稿を作成
POST http://localhost:3000/api/posts HTTP/1.1
Content-Type: application/json

{
  "title": "Test Post",
  "body": "This is a test post.",
  "tags": ["test", "example"],
  "author_id": 10
}

###
# 投稿を更新
PUT http://localhost:3000/api/posts/6 HTTP/1.1
Content-Type: application/json

{
  "title": "Updated Post",
  "body": "This post has been updated.",
  "tags": ["updated"]
}

###
# 投稿を削除
DELETE http://localhost:3000/api/posts/6 HTTP/1.1
